version: "3"
services:

  # API
  app:
    build:
      context: .
      dockerfile: ./Docker/article_server/Dockerfile
    container_name: api
    depends_on:
      - postgres
    volumes:
      - ./article_server:/usr/src/app
    ports:
      - "8000:8000"
    secrets:
      - qiita_api_key
      - POSTGRES_PASSWORD
    command:
      [
        "uvicorn",
        "main:app",
        "--reload",
        "--host",
        "0.0.0.0"
      ]

  # BFF
  apollo:
    # image: node:17
    build:
      context: .
      dockerfile: ./Docker/apollo_server/Dockerfile
    container_name: apollo
    volumes:
      - ./apollo_server:/usr/src/app
    depends_on:
      - postgres
    ports:
      - 4000:4000
    secrets:
      - POSTGRES_PASSWORD
    command: >
      bash -c " npx prisma migrate dev --name init && npm run start"

  # DB
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: t4t5u0
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: "pg"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: portfolio-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./Docker/frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    command: >
      bash -c "npm run build && npm run start"

secrets:
  qiita_api_key:
    file: ./secrets/qiita_api_key.json
  POSTGRES_PASSWORD:
    file: ./secrets/password.txt
