version: "3"
services:

# API
  app:
    build: 
      context: .
      dockerfile: ./Docker/ArticleServer/Dockerfile
    container_name: api
    depends_on:
      - postgres
    volumes:
      - ./article_server:/usr/src/app
    ports:
      - "8000:8000"
    secrets:
      - qiita_api_key
      - POSTGRES_PASSWORD
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]

# BFF
  apollo:
    image: node:17
    container_name: apollo
    volumes:
      - ./apollo_server:/usr/src/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/pg

    secrets:
      - POSTGRES_PASSWORD
    command: ["npm", "run","dev"] # for dev version

# DB
  postgres:
    image: postgres:14.0
    environment:
      POSTGRES_USER: t4t5u0
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB: "pg"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: portfolio-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD
    restart: always

secrets:
  qiita_api_key:
    file: ./secrets/qiita_api_key.json
  POSTGRES_PASSWORD:
    file: ./secrets/password.txt